config/routes.rb
Rails.application.routes.draw do
  root 'pages#one'
  get 'pages/one'
  get 'pages/two'
  get 'pages/three'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def one
  end

  def two
  end

  def three
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= csrf_meta_tags %>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <!--<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button> -->
          <a class="navbar-brand" href="#">First App</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to "Page one", root_path%></li>
            <li><%= link_to "Page two", pages_two_path%></li>
            <li><%= link_to "Page three", pages_three_path%></li>
          </ul>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/pages/one.html.erb
<h1>Manuel Alejandro Olmos Soto</h1>

app/views/pages/three.html.erb
<div class='container'>
    <div class='row'>
        <div class='col-md-12'>
        <h2> Page 3 </h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean laoreet sem vel orci sollicitudin, vel laoreet nibh semper.
        Ut sodales vehicula enim, et sagittis lacus aliquet sed. Nam auctor dui ut dui semper, sit amet volutpat tellus viverra. Pellentesque
        eleifend lectus non quam cursus posuere. Nullam nec mattis velit. Phasellus fringilla rutrum posuere. Quisque a urna a lacus tristique
        dictum vitae eu nisl. Aenean feugiat ipsum in nulla viverra, eget tincidunt sem porta. Vestibulum rutrum scelerisque ipsum eget vehicula.
        Integer volutpat mauris vel tortor maximus, id interdum sapien interdum. Etiam ultricies vitae risus id lacinia. Pellentesque nibh risus,
        ultricies commodo mi in, volutpat interdum orci. Proin a elit eros.</p>
        </div>
    </div>
</div>

app/views/pages/two.html.erb
<h1 class='text-center'>Rake Routes Screenshot</h1>

<div>
<%=image_tag(("rake_routes.png"), :class => "img-thumbnail")%>
</div>